### PR TITLE
Build Update

### PR DESCRIPTION
**Pull request by genio**
Hi!  I received your dist in the last [Pull Request Challenge](http://cpan-prc.org/). There were a few minor build config changes I saw that could help clean things up a bit.

No actual code changes are present.

* Add a .mailmap to help organize the contributors
* Update the dzil build to use the ```@Starter``` module rather than ```@Basic```.
* Update the cpanfile to reflect all of the prereqs
  * Add Net::Twitter
  * Add strict
  * Add warnings
  * Add base
  * Add ExtUtils::MakeMaker
  * Remove Dist::Zilla::Plugin::VersionFromModule
* Include several extra tests for POD Syntax, spelling, etc.
  * Update some spelling errors after including some extra tests.
  * Make some things render in POD ```C<>``` tags so they aren't considered text to spell check
* Remove the 00-load.t
  * Use xt/author/00-compile.t instead (automated)
* Use the Git plugins rather than the direct Metadata plugin
* Remove shebang and ```-w``` flags from all tests

### CODE REVIEW

**Comment by semifor** [comment]
Thanks for all your work on this @genio!

**Comment by semifor** [comment]
@genio after merging, I'm running into an error I need to hunt down before releasing:

```
$ carton exec dzil test
[DZ] building distribution under .build/HKWUltpT2L for installation
[DZ] beginning to build POE-Component-Server-Twirc
[DZ] guessing dist's main_module is lib/POE/Component/Server/Twirc.pm
[Prereqs::FromCPANfile] Parsing 'cpanfile' to extract prereqs
Duplication of element provides.POE::Component::Server::Twirc::State at /Users/marc/devel/perl/twirc/local/lib/perl5/Dist/Zilla.pm line 594.
```

**Comment by genio** [comment]
Let me ```cpan-outdated -p | cpanm``` and see if I can replicate that.

**Comment by genio** [comment]
There was one small set of warnings that I was able to fix with:
```diff
diff --git a/dist.ini b/dist.ini
index b589ae0..fa38ec8 100644
--- a/dist.ini
+++ b/dist.ini
@@ -34,7 +34,6 @@ user = semifor
 [@Git]
 tag_format = %v

-[CheckChangeLog]
 [CheckChangesHasContent]
 [Test::ChangesHasContent]

@@ -50,7 +49,7 @@ skip = POE::Component::Server::Twirc
 skip = POE::Component::Server::Twirc::State

 [Test::PodSpelling]
-wordlist = Pod::WordList
+; wordlist = Pod::WordList
 spell_cmd = aspell list
 stopword = configfile
 stopword = favoriting
```

But I am not seeing the same error/warning you got. Are you Dzil and plugins installs up to date?

```log
macmini-4312:twirc cwhitener$ dzil test
[DZ] building distribution under .build/LXEM5bdGmS for installation
[DZ] beginning to build POE-Component-Server-Twirc
[DZ] guessing dist's main_module is lib/POE/Component/Server/Twirc.pm
[Prereqs::FromCPANfile] Parsing 'cpanfile' to extract prereqs
[DZ] writing POE-Component-Server-Twirc in .build/LXEM5bdGmS
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for POE::Component::Server::Twirc
Writing MYMETA.yml and MYMETA.json
cp lib/POE/Component/Server/Twirc/State.pm blib/lib/POE/Component/Server/Twirc/State.pm
cp lib/App/Twirc/Plugin/SquashWhiteSpace.pm blib/lib/App/Twirc/Plugin/SquashWhiteSpace.pm
cp lib/POE/Component/Server/Twirc/LogAppender.pm blib/lib/POE/Component/Server/Twirc/LogAppender.pm
cp lib/App/Twirc/Plugin/SecondaryAccount.pm blib/lib/App/Twirc/Plugin/SecondaryAccount.pm
cp lib/App/Twirc/Plugin/BangCommands.pm blib/lib/App/Twirc/Plugin/BangCommands.pm
cp lib/POE/Component/Server/Twirc.pm blib/lib/POE/Component/Server/Twirc.pm
cp lib/App/Twirc/Manual.pod blib/lib/App/Twirc/Manual.pod
cp lib/App/Twirc.pm blib/lib/App/Twirc.pm
cp bin/twirc blib/script/twirc
"/Users/cwhitener/perl5/perlbrew/perls/perl-5.26.0/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/twirc
PERL_DL_NONLAZY=1 "/Users/cwhitener/perl5/perlbrew/perls/perl-5.26.0/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-report-prereqs.t ............ #
# Versions for all modules listed in MYMETA.json (including optional ones):
#
# === Configure Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.30
#
# === Build Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.30
#     strict               any 1.11
#     warnings             any 1.37
#
# === Test Requires ===
#
#     Module              Want     Have
#     ------------------- ---- --------
#     ExtUtils::MakeMaker  any     7.30
#     File::Spec           any     3.67
#     Test::More           any 1.302086
#     strict               any     1.11
#     warnings             any     1.37
#
# === Test Recommends ===
#
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150010
#
# === Runtime Requires ===
#
#     Module                         Want       Have
#     --------------------------- ------- ----------
#     AnyEvent                        any       7.14
#     AnyEvent::Twitter               any       0.64
#     AnyEvent::Twitter::Stream      0.23       0.28
#     Config::Any                     any       0.32
#     Encode                          any       2.92
#     FindBin                         any       1.51
#     HTML::Entities                  any       3.69
#     JSON::MaybeXS                   any   1.003009
#     Log::Log4perl                   any       1.49
#     Moose                           any     2.2006
#     MooseX::Getopt                 0.15       0.71
#     MooseX::Log::Log4perl::Easy     any       0.47
#     MooseX::POE                   0.215      0.215
#     MooseX::SimpleConfig            any       0.11
#     MooseX::Storage                 any       0.52
#     Net::Twitter                    any    4.01042
#     POE::Component::Server::IRC 0.02005       1.54
#     POE::Component::TSTP            any       0.02
#     POE::Loop::AnyEvent             any      0.004
#     Path::Class::File               any       0.37
#     Proc::Daemon                    any       0.23
#     Regexp::Common::URI             any 2017060201
#     Scalar::Util                    any       1.48
#     String::Truncate                any   1.100602
#     Try::Tiny                       any       0.28
#     base                            any       2.25
#     strict                          any       1.11
#     utf8                            any       1.19
#     warnings                        any       1.37
#
# === Develop Requires ===
#
#     Module                                     Want     Have
#     ------------------------------------------ ---- --------
#     Archive::Tar::Wrapper                      0.15     0.23
#     Dist::Zilla                                 any    6.010
#     Dist::Zilla::Plugin::Prereqs::FromCPANfile  any     0.08
#     Dist::Zilla::PluginBundle::Starter          any    0.005
#     File::Spec                                  any     3.67
#     IO::Handle                                  any     1.36
#     IPC::Open3                                  any     1.20
#     Pod::Coverage::TrustPod                     any 0.100003
#     Test::Kwalitee                             1.21     1.26
#     Test::More                                 0.88 1.302086
#     Test::Pod                                  1.41     1.51
#     Test::Pod::Coverage                        1.08     1.10
#     Test::Spelling                             0.12     0.20
#     Test::Version                                 1     2.05
#
t/00-report-prereqs.t ............ ok
t/40-plugin-bang-commands.t ...... ok
t/40-plugin-secondary-account.t .. ok
t/40-plugin-squash-whitespace.t .. ok
All tests successful.
Files=4, Tests=20,  1 wallclock secs ( 0.02 usr  0.02 sys +  0.86 cusr  0.09 csys =  0.99 CPU)
Result: PASS
xt/author/00-compile.t .... ok
xt/author/pod-coverage.t .. ok
xt/author/pod-spell.t ..... ok
xt/author/pod-syntax.t .... ok
xt/author/test-version.t .. ok
All tests successful.
Files=5, Tests=39,  4 wallclock secs ( 0.04 usr  0.03 sys +  3.75 cusr  0.33 csys =  4.15 CPU)
Result: PASS
[DZ] all's well; removing .build/LXEM5bdGmS
```

**Comment by semifor** [comment]
Dzil and plugins are up-to-date. This seems to fix it:

```diff
diff --git a/dist.ini b/dist.ini
index b589ae0..4ebbb74 100644
--- a/dist.ini
+++ b/dist.ini
@@ -21,7 +21,6 @@ Test::Compile.skip[1] = POE::Component::Server::Twirc::LogAppender
 [PkgVersion]
 
 [Prereqs::FromCPANfile]
-[MetaProvides::Package]
 
 [Meta::Contributors]
 contributor = Adam Prime <adam.prime@utoronto.ca>
```

**Pull request merged**
