### PR TITLE
Add modules required for build to README

### PR DESCRIPTION
**Pull request by pwr22**
Also rebuilds README pulling in twitter_args

### CODE REVIEW

**Comment by pwr22** [comment]
A bit more info on this. As someone who's never used module::install I had to work this out before I could get on with contributing anything. So I added this new section to remove that barrier for anyone else in the future

**Comment by semifor** [comment]
I haven't merged this one yet, because I want to take a look when I have a bit of time. I'm not sure this is strictly correct. Rather than BUILDING, perhaps CONTRIBUTING. I don't think you need the additional modules to build twirc if you install it from CPAN. But you do if you're working with the github repo. I need to verify.

**Comment by pwr22** [comment]
Ah yes, I mean building the distribution, I'll make it clearer

Peter

**Comment by pwr22** [comment]
I've updated the docs again, hopefully this makes it clearer

**Comment by semifor** [comment]
Thanks! That works!

**Pull request merged**
