### PR TITLE
Remove rate_limit_status, it no longer works and isn't useful

### PR DESCRIPTION
**Pull request by pwr22**
Even if it did, with the 1.1 API limiting there is no meaningful way to display
it all

rate_limit_status gives a error 400 but it should still work, the endpoint
exists, Net::Twitter may have an issue

### CODE REVIEW

**Comment by pwr22** [comment]
Errors look like this

    07:55:21 [INFO] Received request https://api.twitter.com/1.1/application/rate_limit_status.json?
    07:58:36 [INFO] Response from https://api.twitter.com/1.1/application/rate_limit_status.json? arrived (400)
    07:58:36 [ERROR] twitter errer: 400 Bad Request at /home/peter/.perlbrew/libs/5.20.1@twirc/lib/perl5/x86_64-linux/Class/MOP/Method/Wrapped.pm line 158

**Comment by semifor** [comment]
I'm not sure what's up here. `rate_limit_status` works for me. The response is in API v1.1 is very different, but it's returning 200, not 400. I think I'd rather modify it to take arguments and change the output than remove it. I'll investigate.

FYI, I fixed the spelling error is that message: 78253e8.

**Comment by pwr22** [comment]
Did you test via Twirc or directly with Net::Twitter

I have not tried the latter yet, but there are a few other commands failing for me. If testing in Twirc, does favourite work for you?

**Comment by semifor** [comment]
I tested Net::Twitter directly. Haven't set up twirc to test it, yet.

**Comment by pwr22** [comment]
I'll try the direct approach a bit later, but will have to be with my own App keys, unless I extract those from Twirc

I initially found my keys didn't work properly when manually testing, and had to regenerate both App and cllient keys, then it worked fine. Maybe something similar could be going on here (i.e. a problem on twitter's end)?

**Comment by pwr22** [comment]
And how would you like to condense / format all these limits?

https://dev.twitter.com/rest/public/rate-limits

**Comment by semifor** [comment]
I'd have the `rate_limit_status` command take an optional argument, the API method (the Net::Twitter name for the method), and extract that limit from the results for display.

Without arguments, I'd filter the result and show the limits that have been exceeded, or are closest to being exceeded. Top 3 or 4. Whatever fits comfortably on a single line.

**Comment by pwr22** [comment]
My view is that maintaining this feature would be a waste. For Net::Twitter, an API, it is obviously useful as a program can make intelligent decisions based on rate limit data. For Twirc, a twitter client, it is not useful as I can't envisage any scenario where a human would use it, and how they could meaningfully act on the results

What I mean is that if you want to post a tweet you're going to do that, and if it fails you will be told. No need to manually check first. Nothing to do when it fails but wait

When you used to use Twirc how often did you use the command? All the other twitter gateways I've looked at don't provide this command

**Comment by pwr22** [comment]
I've tested Net::Twitter with both my own and Twirc's keys and rate_limit_status works in both cases. I am uncertain why Twirc itself claims failure

I am uncertain how to test successfully using LWP::UserAgent::POE

**Comment by pwr22** [comment]
Hmm, actually it looks like it does work, it is just failing (looks like a timeout) after a few minutes. Same error (400) as twirc. This looks to be the source of the problem

**Comment by semifor** [comment]
As discussed on IRC, closing this with the intent to "fix" this feature rather than remove it.

**Pull request closed without merging**
